"""
Interactive configuration helper
Run this to set up your .env file
"""

import os
from pathlib import Path

def validate_email(email):
    """Basic email validation"""
    return '@' in email and '.' in email

def validate_api_key(key):
    """Basic OpenAI API key validation"""
    return key.startswith('sk-') and len(key) > 20

def create_env_file():
    """Interactive .env file creation"""
    print("="*60)
    print("LLM Analysis Quiz - Configuration Setup")
    print("="*60)
    print("\nThis script will help you create your .env file.\n")
    
    env_path = Path('.env')
    
    if env_path.exists():
        overwrite = input(".env file already exists. Overwrite? (y/N): ").lower()
        if overwrite != 'y':
            print("Setup cancelled.")
            return
    
    # Collect information
    print("\n1. Student Email")
    print("   Enter your student email address:")
    while True:
        email = input("   > ").strip()
        if validate_email(email):
            break
        print("   ❌ Invalid email format. Please try again.")
    
    print("\n2. Secret Key")
    print("   Enter a unique secret string for authentication:")
    print("   (This will be used to verify quiz requests)")
    secret = input("   > ").strip()
    while not secret:
        print("   ❌ Secret cannot be empty.")
        secret = input("   > ").strip()
    
    print("\n3. OpenAI API Key")
    print("   Enter your OpenAI API key:")
    print("   (Get one from: https://platform.openai.com/api-keys)")
    while True:
        api_key = input("   > ").strip()
        if validate_api_key(api_key):
            break
        print("   ❌ Invalid API key format. Should start with 'sk-'")
    
    print("\n4. Server Port")
    print("   Default is 5000. Press Enter to use default, or type a different port:")
    port_input = input("   > ").strip()
    port = port_input if port_input else "5000"
    
    print("\n5. Debug Mode")
    print("   Enable debug mode? (Y/n):")
    debug_input = input("   > ").lower().strip()
    debug = "False" if debug_input == 'n' else "True"
    
    # Create .env content
    env_content = f"""# LLM Analysis Quiz - Environment Configuration
# Generated by configure_env.py

# Student Information
STUDENT_EMAIL={email}
SECRET_KEY={secret}

# API Keys
OPENAI_API_KEY={api_key}

# Server Configuration
PORT={port}
DEBUG={debug}
"""
    
    # Write file
    env_path.write_text(env_content)
    
    print("\n" + "="*60)
    print("✓ Configuration complete!")
    print("="*60)
    print("\nYour .env file has been created with the following settings:")
    print(f"  Email:     {email}")
    print(f"  Secret:    {'*' * len(secret)}")
    print(f"  API Key:   {api_key[:10]}...")
    print(f"  Port:      {port}")
    print(f"  Debug:     {debug}")
    print("\n⚠️  IMPORTANT:")
    print("  - Never commit your .env file to Git")
    print("  - Keep your secret and API key secure")
    print("  - Use the same secret in the Google Form")
    print("\nNext steps:")
    print("  1. Run: python app.py")
    print("  2. Test: python test_endpoint.py")
    print("  3. Check GOOGLE_FORM_GUIDE.md for submission instructions")
    print("="*60)

if __name__ == '__main__':
    try:
        create_env_file()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        print("Please check your inputs and try again.")
